// tests/beat-blocker.chart.test.mjs
//
// Beat Blocker has no music to sync to — engine/audio.js synthesises tones and
// there is no backend to fetch a track from — so the chart is the source of
// truth and the music is generated from it. That inversion is what makes this
// file possible: every question about whether the game is fair is a question
// about numbers, and none of it needs a speaker.
//
// The claim, and it is convention 11 applied to the one genre that is made
// entirely of timing windows:
//
//   THE WINDOW IS ONE A PERSON CAN HIT, AT EVERY TEMPO, AND THE SHIELD CAN
//   ALWAYS PHYSICALLY GET THERE.
//
// Two ways that goes wrong, both guarded below. A window measured in beats
// silently shrinks as the tempo climbs. And a pattern can ask the shield to be
// in two places at once, which is not difficulty — it is a chart that cannot
// be played.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  END, JUDGE, Session, TUNING, beatSeconds, bpmAt, breaches, buildPhrase,
  densityFor, judge, movementFor, reachMs, subdivisionFor, tightestGaps,
} from '../games/beat-blocker/chart.js';
import { SKILLS, runOnce } from './helpers/beat-bot.mjs';
import { summarise, withSeed } from './helpers/seeded.mjs';

/**
 * Every attack a session deals over `phrases` phrases, in one flat list.
 *
 * The chart is one list on one clock now, so this is a matter of running the
 * session and collecting -- there is no per-phrase list to stitch back together
 * and no seam to get wrong while stitching it.
 */
function chartAcross(phrases, tuning = TUNING) {
  const session = new Session(tuning);
  const seen = new Map();
  let guard = 0;
  while (session.phrase <= phrases && guard++ < 4_000_000) {
    for (const event of session.events) if (!seen.has(event.id)) seen.set(event.id, { ...event });
    session.hearts = tuning.hearts + 99;      // never end the run; this is about the chart
    session.step(1 / 30, {});
  }
  return [...seen.values()].sort((a, b) => a.time - b.time);
}

/**
 * How much warning each attack got: the gap between first appearing in the
 * session's list and having to be blocked.
 */
function warnings(phrases, tuning = TUNING) {
  const session = new Session(tuning);
  const first = new Map();
  let guard = 0;
  while (session.phrase <= phrases && guard++ < 4_000_000) {
    for (const event of session.events) {
      if (!first.has(event.id)) first.set(event.id, event.time - session.time);
    }
    session.hearts = tuning.hearts + 99;
    session.step(1 / 120, {});
  }
  return [...first.values()];
}

// --- The window -----------------------------------------------------------

test('THE JUDGING WINDOW IS IN MILLISECONDS AND DOES NOT MOVE WITH THE TEMPO', () => {
  // The classic way to make a rhythm game unplayable at speed without noticing.
  // At 84bpm an eighth of a beat is 89ms and generous; at 260bpm the same
  // eighth is 29ms and frame-perfect. Nothing here is a fraction of a beat, so
  // a faster phrase asks for more, not for more precision.
  assert.equal(judge(0), JUDGE.PERFECT);
  assert.equal(judge(TUNING.perfectMs - 1), JUDGE.PERFECT);
  assert.equal(judge(TUNING.perfectMs + 1), JUDGE.GOOD);
  assert.equal(judge(TUNING.goodMs + 1), null);
  // Early and late are the same. A game that forgives late presses more than
  // early ones teaches you to lag.
  assert.equal(judge(-40), judge(40));
  assert.equal(judge(-200), judge(200));

  // And the windows genuinely are constants rather than anything derived: the
  // same delta is judged identically under tunings whose tempos differ and
  // whose everything else is the same.
  const slow = { ...TUNING, bpmBase: 60 };
  const fast = { ...TUNING, bpmBase: 240 };
  for (const delta of [10, 54, 56, 114, 116, 300]) {
    assert.equal(judge(delta, slow), judge(delta, fast),
      `${delta}ms is judged differently at a different tempo`);
  }
});

test('the window is above a human floor', () => {
  // Convention 11. A window nobody can hit is not difficulty. Fifty-five
  // milliseconds either side of the beat for a PERFECT is about three frames at
  // sixty hertz; a hundred and fifteen for a hit is comfortably inside what a
  // person can do without practising.
  assert.ok(TUNING.perfectMs >= 45, 'the perfect window is tighter than a frame or two');
  assert.ok(TUNING.goodMs >= 100, 'the hit window is tighter than ordinary reaction slop');
  assert.ok(TUNING.perfectMs < TUNING.goodMs, 'precision buys nothing');
});

// --- Reachability ---------------------------------------------------------

test('THE SHIELD CAN ALWAYS GET THERE — every phrase, including across the seams', () => {
  // The chart is generated by placing notes at reachable times rather than by
  // generating densely and deleting what does not fit, and this is the
  // independent walk over the result. Two hundred phrases takes it well past
  // the tempo cap and into the subdivided end of the game.
  for (let seed = 1; seed <= 6; seed++) {
    withSeed(seed, () => {
      const found = breaches(chartAcross(200));
      assert.equal(found.length, 0, found.length
        ? `seed ${seed}: ${found[0].gap.toFixed(0)}ms for a move needing ${found[0].need}ms`
        : '');
    });
  }
});

test('and the distance between lanes is in the arithmetic', () => {
  // The first version used one flat floor for any lane change, which is right
  // for next door and a lie for the far side. Charts passed it and it still
  // cost a bot with zero jitter a heart every few phrases.
  assert.ok(reachMs(0, 2) > reachMs(0, 1), 'crossing two lanes is treated as crossing one');
  assert.equal(reachMs(1, 1), TUNING.sameLaneFloorMs);
  assert.equal(reachMs(0, 2), 2 * TUNING.laneMoveMs + TUNING.laneMarginMs);
});

test('breaches() actually reports a breach when there is one', () => {
  // A checker that cannot fail is not a check. Same class as the assertion that
  // pinned an accident (tests/README.md, convention 12): the test above passes
  // trivially if breaches() always returns nothing.
  const impossible = [{ time: 0, lane: 0 }, { time: 0.05, lane: 2 }];
  assert.equal(breaches(impossible).length, 1);
});

test('the shield takes real time to cross a lane', () => {
  // Which is what any of the above means. If the shield were in every lane at
  // once the floors would guard nothing and this would be a one-button game
  // with three columns drawn behind it.
  const session = new Session();
  session.events = [];
  session.lane = 2;
  session.shield = 2;
  const steps = Math.round((TUNING.laneMoveMs / 1000) * 120);
  for (let i = 0; i < steps - 6; i++) session.step(1 / 120, { lane: 1 });
  assert.ok(session.shield > 1, 'the shield arrived instantly');
  for (let i = 0; i < 12; i++) session.step(1 / 120, { lane: 1 });
  assert.equal(session.shield, 1);
});

test('a press only counts in the lane the shield is covering', () => {
  const session = new Session();
  session.events = [{ id: 'x', time: session.time, lane: 0, done: false }];
  session.lane = 0;
  session.shield = 2;                       // still on the far side
  assert.equal(session.block(), null, 'a press landed in a lane the shield was not in');
  session.shield = 0;
  assert.equal(session.block(), JUDGE.PERFECT);
});

// --- The opening ----------------------------------------------------------

test('EVERY ATTACK ENTERS FROM THE SPAWN LINE AND TRAVELS', () => {
  // The fault this test was written for, and it shipped: the chart used to be
  // dealt a phrase at a time, at the moment the phrase began, so an attack in
  // the first approach-second of a phrase had never been on screen. Measured
  // over eight phrases, 18 of 78 attacks appeared with less than the full
  // approach and the FIRST attack of most phrases appeared at the strike line
  // with a warning of -0.001 seconds. Unblockable, and every other test passed.
  //
  // The reachability floors were never wrong -- they are about whether the
  // SHIELD can get there, and it could. Nothing was about whether the player
  // could see it coming. Convention 10: right about what it measures, blind to
  // everything else.
  for (const seed of [1, 3, 7]) {
    withSeed(seed, () => {
      const seen = warnings(12);
      const worst = Math.min(...seen);
      assert.ok(seen.length > 60, 'not enough attacks to prove anything');
      assert.ok(worst >= TUNING.approachSeconds - 1e-6,
        `an attack appeared with ${worst.toFixed(3)}s of warning against an approach `
        + `of ${TUNING.approachSeconds}s`);
    });
  }
});

test('and the chart is dealt further ahead than the screen is deep', () => {
  // Which is the mechanism behind the test above rather than a restatement of
  // it: what is dealt has to cover the whole approach with room for a slow
  // frame, or attacks would pop in again the moment the machine hiccupped.
  withSeed(5, () => {
    const session = new Session();
    for (let i = 0; i < 2000; i++) {
      session.hearts = TUNING.hearts + 99;
      session.step(1 / 60, {});
      assert.ok(session.dealtTo >= session.time + TUNING.approachSeconds,
        'the chart ran out in front of the player');
    }
  });
});

test('nothing is thrown at the player before the run-up is over', () => {
  // CLAUDE.md: the run-up before the first real threat is a number somebody
  // chose and can point at. Here it is leadInBeats, and it exists so the first
  // thing a player does is hear the tempo rather than lose a heart to it.
  withSeed(3, () => {
    const session = new Session();
    assert.ok(session.time < 0, 'the run starts on the first attack');
    const lead = TUNING.leadInBeats * beatSeconds(bpmAt(1));
    assert.ok(Math.abs(session.time + lead) < 1e-9);
    const first = session.events[0];
    assert.ok(first.time - session.time >= lead - 1e-9,
      'the first attack arrives inside the run-up');
    // And the shield starts where the run-up says it does, because the run-up
    // is the seam anchor: there is nowhere to have moved from yet.
    assert.equal(session.shield, Math.floor(TUNING.lanes / 2));
  });
});

// --- Escalation -----------------------------------------------------------

test('the tempo climbs, then hands over to the subdivision', () => {
  assert.ok(bpmAt(10) > bpmAt(1));
  assert.ok(bpmAt(30) > bpmAt(10));
  assert.equal(bpmAt(500), TUNING.bpmMax, 'the tempo climbs without limit');
  // Past the cap the pulse stays readable and the notes keep coming faster,
  // because a beat quicker than a person can tap is not a harder game — it is
  // the same game with a bigger number on it.
  assert.equal(subdivisionFor(1), 1);
  assert.ok(subdivisionFor(200) > subdivisionFor(1));
  assert.ok(densityFor(30) > densityFor(1));
});

test('and MOVEMENT is what escalates after the tempo has run out', () => {
  // Measured, not assumed. This is the axis that carries the late game: the
  // reachability floors mean packing in more notes only gets them placed
  // further apart, so the same music spread wider is the room that is left.
  const shape = (phrase) => withSeed(11, () => {
    const events = buildPhrase(phrase);
    const seconds = TUNING.beatsPerPhrase * beatSeconds(bpmAt(phrase));
    let lanesCrossed = 0;
    for (let i = 1; i < events.length; i++) {
      lanesCrossed += Math.abs(events[i].lane - events[i - 1].lane);
    }
    return { rate: events.length / seconds, movement: lanesCrossed / seconds };
  });

  assert.ok(shape(20).rate > shape(1).rate * 1.5, 'the early game does not get busier');
  assert.ok(shape(60).movement > shape(1).movement * 3,
    'the late game asks for no more moving about than the first phrase does');
  assert.ok(movementFor(80).cross > movementFor(1).cross);
  assert.ok(movementFor(80).far > movementFor(1).far);
});

test('a fast phrase is not a phrase of impossible taps', () => {
  // The other half of convention 11: the escalation is allowed to make the
  // chart busier and it is not allowed to make it faster than a hand.
  withSeed(5, () => {
    for (const phrase of [1, 20, 60, 120, 300]) {
      const gaps = tightestGaps(buildPhrase(phrase));
      assert.ok(gaps.sameLane >= TUNING.sameLaneFloorMs - 1e-6,
        `phrase ${phrase} asks for two taps ${gaps.sameLane.toFixed(0)}ms apart`);
    }
  });
});

// --- The claim ------------------------------------------------------------

test('PLAYING TO THE BEAT BEATS MASHING, and by a distance', () => {
  // The null hypothesis for any rhythm game: that pressing at a steady rate of
  // your own does nearly as well as playing the chart. If that were true the
  // music would be decoration and the game would be a button.
  const scores = {};
  for (const skill of ['onBeat', 'masher']) {
    scores[skill] = [];
    for (let seed = 1; seed <= 40; seed++) {
      withSeed(seed, () => scores[skill].push(runOnce(skill, undefined, { phrases: 20 }).score));
    }
  }
  const onBeat = summarise(scores.onBeat);
  const masher = summarise(scores.masher);
  assert.ok(onBeat.median > masher.median * 10,
    `mashing keeps up: ${onBeat.median} against ${masher.median}`);
  // And not by outliving it — by scoring. The masher dies; that is the point.
  assert.ok(masher.max < onBeat.min, 'the best mash beat the worst timed run');
});

test('the two bots differ in exactly one field', () => {
  // Otherwise the gap above could be measuring anything. Same movement, same
  // slop, same button; the only difference is when the press happens.
  const keys = new Set(Object.values(SKILLS).flatMap((s) => Object.keys(s)));
  assert.deepEqual([...keys], ['readsChart']);
  assert.notEqual(SKILLS.onBeat.readsChart, SKILLS.masher.readsChart);
});

test('PRECISION PAYS AND SLOP IS SURVIVABLE — the window is a slope, not a cliff', () => {
  // Both halves matter. A player who is roughly on the beat should live and
  // score less; a player outside the window should not live. The first version
  // had a cliff here — 90% survival at 45ms of slop, 0% at 60ms — and the cause
  // was worth finding: the bot stood over a note whose window had not expired
  // even once the shield could no longer reach it, so one miss took the next
  // note with it. That was the bot, not the chart.
  const at = (jitterMs) => {
    const scores = [];
    let survived = 0;
    for (let seed = 1; seed <= 30; seed++) {
      withSeed(seed, () => {
        const run = runOnce('onBeat', undefined, { jitterMs, phrases: 20 });
        scores.push(run.score);
        if (run.survived) survived++;
      });
    }
    return { median: summarise(scores).median, survival: survived / 30 };
  };

  const tight = at(0);
  const loose = at(90);
  const outside = at(150);

  assert.ok(loose.survival >= 0.9,
    `90ms of slop is fatal ${((1 - loose.survival) * 100).toFixed(0)}% of the time`);
  assert.ok(loose.median < tight.median * 0.95, 'being sloppy costs nothing, so precision is free');
  assert.ok(outside.survival < 0.2, 'pressing outside the window survives, so the window is decoration');
});

// --- The session ----------------------------------------------------------

test('a miss costs a heart, and running out ends the run for a stated reason', () => {
  const session = new Session();
  session.events = [{ id: 'x', time: session.time - 1, lane: session.lane, done: false }];
  const before = session.hearts;
  session.step(1 / 60, {});
  assert.equal(session.hearts, before - 1);
  assert.equal(session.streak, 0);

  session.hearts = 1;
  session.events = [{ id: 'y', time: session.time - 1, lane: session.lane, done: false }];
  session.step(1 / 60, {});
  assert.equal(session.running, false);
  assert.equal(session.reason, END.OVERWHELMED);
});

test('a clean run of blocks buys a heart back', () => {
  // Without this, four hearts and no way to recover made an endless game into a
  // pass/fail exam: a couple of hundred attacks will find any miss rate above
  // about two per cent, so a small change in slop flipped survival from nearly
  // always to never.
  const session = new Session();
  session.hearts = 1;
  session.events = [];
  for (let i = 0; i < TUNING.healStreak; i++) {
    session.events.push({ id: `h${i}`, time: session.time, lane: session.lane, done: false });
    session.block();
  }
  assert.equal(session.hearts, 2);
  assert.ok(session.hearts <= TUNING.hearts);
});

test('a perfect block is worth more than a scrambled one', () => {
  assert.ok(TUNING.perfectScore > TUNING.goodScore,
    'timing to the beat and merely getting there pay the same');
});

test('tuning is data a test can override', () => {
  // Convention 3. Make the shield crawl and the chart must space its crossings
  // further apart — if the generator were ignoring the figure this would
  // produce a chart full of moves the shield could never make.
  const crawling = { ...TUNING, laneMoveMs: 420 };
  const movesIn = (list) => list.filter((e, i) => i && e.lane !== list[i - 1].lane).length;
  const slow = withSeed(8, () => buildPhrase(40, crawling));
  const normal = withSeed(8, () => buildPhrase(40));
  assert.equal(breaches(slow, crawling).length, 0);
  assert.ok(movesIn(slow) < movesIn(normal),
    'a slower shield was asked to do the same amount of moving');
});
