// tools/build-sitemap.mjs
//
// Writes public/sitemap.xml from games.json, so the sitemap cannot drift from
// the games that actually exist. Hand-maintaining it would mean every new
// game is two edits, and the second one gets forgotten.
//
// Run: node tools/build-sitemap.mjs
// It is deliberately NOT wired into the build. The sitemap changes only when
// a game ships, which is a moment worth looking at the diff for.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// The one place the deployed host is written down. Changing to a custom
// domain is this line, plus the canonical and og:url tags in the pages.
const ORIGIN = 'https://studio22-anw.pages.dev';

const games = JSON.parse(fs.readFileSync(path.join(ROOT, 'games.json'), 'utf8'));
const list = Array.isArray(games) ? games : games.games;

// Only live games. A coming-soon game has no folder, so listing it would put
// a 404 in the sitemap — which is the one thing a sitemap must never do.
const live = list.filter((game) => game.status === 'live');

const pages = [
  { loc: '/', priority: '1.0', changefreq: 'monthly' },
  { loc: '/arcade.html', priority: '0.9', changefreq: 'monthly' },
  { loc: '/party.html', priority: '0.7', changefreq: 'monthly' },
  ...live.map((game) => ({ loc: game.path, priority: '0.8', changefreq: 'monthly' })),
];

const today = new Date().toISOString().slice(0, 10);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/build-sitemap.mjs from games.json. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map((page) => `  <url>
    <loc>${ORIGIN}${page.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;

const out = path.join(ROOT, 'public', 'sitemap.xml');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, xml);

console.log(`sitemap.xml written with ${pages.length} URLs (${live.length} live games)`);
for (const page of pages) console.log(`  ${ORIGIN}${page.loc}`);
