// tools/verify-build.mjs
//
// Checks that dist/ actually contains what games.json promises.
//
// WHY THIS EXISTS
// ---------------
// This project's hardest-won lesson is that A FAILED BUILD IS A SILENT
// DEPLOY: engine/canvas.js once had a parse error, `vite build` failed, and
// Cloudflare Pages went on serving the previous version. The site looked
// alive while the repo was broken, and nothing said so.
//
// `npm run build` exiting non-zero catches that case. This catches the
// quieter one: a build that SUCCEEDS but is missing something. A game added
// to games.json whose folder was never created, an entry point dropped from
// the Vite config, a public/ file that stopped being copied. All of those
// produce a green build and a broken site, and none of them are visible
// without asking the manifest what should be there and then looking.
//
// Run: node tools/verify-build.mjs   (CI runs it after every build)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');

const problems = [];
const checked = [];

const exists = (rel) => fs.existsSync(path.join(DIST, rel));

function require_(rel, why) {
  checked.push(rel);
  if (!exists(rel)) problems.push(`missing ${rel} — ${why}`);
}

// --- The build has to exist at all ---------------------------------------

if (!fs.existsSync(DIST)) {
  console.error('dist/ does not exist. The build did not run, or it failed.');
  process.exit(1);
}

// --- Every page the site is made of --------------------------------------

require_('index.html', 'the landing page');
require_('arcade.html', 'the hub');
require_('party.html', 'hot-seat tournaments');

// From public/, so a check that Vite still copies that directory.
require_('_headers', 'the Cloudflare response-header policy, including the CSP');
require_('404.html', 'without it Pages answers 200 with the landing page for every unknown path');
require_('robots.txt', 'crawler policy');
require_('sitemap.xml', 'generated by tools/build-sitemap.mjs');
require_('favicon.svg', 'the tab icon');
require_('site.webmanifest', 'the installable-app manifest');

// --- Every game in the manifest ------------------------------------------

const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'games.json'), 'utf8'));
const games = manifest.games ?? manifest;
const live = games.filter((g) => g.status === 'live');

if (live.length === 0) problems.push('games.json lists no live games at all');

for (const game of live) {
  // `path` is what the hub links to, so that is the file that has to exist.
  const rel = game.path.replace(/^\//, '');
  checked.push(rel);
  if (!exists(rel)) {
    problems.push(`missing ${rel} — games.json lists "${game.id}" as live and the arcade links to it`);
    continue;
  }

  // A page that exists but loads nothing is the black-screen bug again.
  const html = fs.readFileSync(path.join(DIST, rel), 'utf8');
  if (!/<script[^>]+type="module"[^>]+src=/.test(html)) {
    problems.push(`${rel} has no module script — the game would never boot`);
  }
  if (!html.includes('id="boot-fallback"')) {
    problems.push(`${rel} has no #boot-fallback — a module that fails to parse would show a blank page with no explanation`);
  }
}

// A coming-soon game must NOT have a page linked from the hub, because the
// hub renders it inert on purpose.
for (const game of games.filter((g) => g.status !== 'live')) {
  console.log(`  note: "${game.id}" is ${game.status}; the hub will render it inert.`);
}

// --- Nothing that should never ship --------------------------------------

// reference/ is the original prototypes. They are not part of the site and
// deploying them would put two unmaintained copies of two games on the
// domain, outside the shell and outside the CSP's assumptions.
if (exists('reference')) {
  problems.push('reference/ was copied into dist/ — the prototypes must not be deployed');
}

// --- Report ---------------------------------------------------------------

const assets = fs.existsSync(path.join(DIST, 'assets'));
if (!assets) problems.push('dist/assets is missing — nothing was bundled');

if (problems.length) {
  console.error(`\nBUILD VERIFICATION FAILED — ${problems.length} problem(s):\n`);
  for (const p of problems) console.error('  ✗ ' + p);
  console.error('');
  process.exit(1);
}

console.log(`\nBuild verified: ${live.length} live games, ${checked.length} required files all present.`);
